version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nestjs-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_graphql_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/nestjs_graphql_db?schema=public
      NODE_ENV: production
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  postgres_data:
